/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AplicacoesRouteImport } from './routes/aplicacoes'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as ExamesRouteImport } from './routes/exames'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as PacientesRouteImport } from './routes/pacientes'
import { Route as ProntuarioRouteImport } from './routes/prontuario'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as ApiInventorySessionRouteImport } from './routes/api/inventory-session'
import { Route as AplicacoesIndexRouteImport } from './routes/aplicacoes/index'
import { Route as AplicacoesNovaRouteImport } from './routes/aplicacoes/nova'
import { Route as EstoqueIndexRouteImport } from './routes/estoque/index'
import { Route as EstoqueAcessoRouteImport } from './routes/estoque/acesso'
import { Route as EstoqueMovimentacoesRouteImport } from './routes/estoque/movimentacoes'
import { Route as EstoqueRecebimentoRouteImport } from './routes/estoque/recebimento'
import { Route as PacientesPatientIdRouteImport } from './routes/pacientes.$patientId'
import { Route as EstoqueLotesLotIdRouteImport } from './routes/estoque/lotes/$lotId'
import { Route as EstoqueProdutosProductIdRouteImport } from './routes/estoque/produtos/$productId'
import { Route as ApiV1InventorySplatRouteImport } from './routes/api/v1/inventory/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AplicacoesRoute = AplicacoesRouteImport.update({
  id: '/aplicacoes',
  path: '/aplicacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamesRoute = ExamesRouteImport.update({
  id: '/exames',
  path: '/exames',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProntuarioRoute = ProntuarioRouteImport.update({
  id: '/prontuario',
  path: '/prontuario',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInventorySessionRoute = ApiInventorySessionRouteImport.update({
  id: '/api/inventory-session',
  path: '/api/inventory-session',
  getParentRoute: () => rootRouteImport,
} as any)
const AplicacoesIndexRoute = AplicacoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AplicacoesRoute,
} as any)
const AplicacoesNovaRoute = AplicacoesNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AplicacoesRoute,
} as any)
const EstoqueIndexRoute = EstoqueIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EstoqueRoute,
} as any)
const EstoqueAcessoRoute = EstoqueAcessoRouteImport.update({
  id: '/acesso',
  path: '/acesso',
  getParentRoute: () => EstoqueRoute,
} as any)
const EstoqueMovimentacoesRoute = EstoqueMovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => EstoqueRoute,
} as any)
const EstoqueRecebimentoRoute = EstoqueRecebimentoRouteImport.update({
  id: '/recebimento',
  path: '/recebimento',
  getParentRoute: () => EstoqueRoute,
} as any)
const PacientesPatientIdRoute = PacientesPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => PacientesRoute,
} as any)
const EstoqueLotesLotIdRoute = EstoqueLotesLotIdRouteImport.update({
  id: '/lotes/$lotId',
  path: '/lotes/$lotId',
  getParentRoute: () => EstoqueRoute,
} as any)
const EstoqueProdutosProductIdRoute =
  EstoqueProdutosProductIdRouteImport.update({
    id: '/produtos/$productId',
    path: '/produtos/$productId',
    getParentRoute: () => EstoqueRoute,
  } as any)
const ApiV1InventorySplatRoute = ApiV1InventorySplatRouteImport.update({
  id: '/api/v1/inventory/$',
  path: '/api/v1/inventory/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/aplicacoes': typeof AplicacoesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/crm': typeof CrmRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/exames': typeof ExamesRoute
  '/financeiro': typeof FinanceiroRoute
  '/pacientes': typeof PacientesRouteWithChildren
  '/prontuario': typeof ProntuarioRoute
  '/vendas': typeof VendasRoute
  '/api/inventory-session': typeof ApiInventorySessionRoute
  '/aplicacoes/nova': typeof AplicacoesNovaRoute
  '/estoque/acesso': typeof EstoqueAcessoRoute
  '/estoque/movimentacoes': typeof EstoqueMovimentacoesRoute
  '/estoque/recebimento': typeof EstoqueRecebimentoRoute
  '/pacientes/$patientId': typeof PacientesPatientIdRoute
  '/aplicacoes/': typeof AplicacoesIndexRoute
  '/estoque/': typeof EstoqueIndexRoute
  '/estoque/lotes/$lotId': typeof EstoqueLotesLotIdRoute
  '/estoque/produtos/$productId': typeof EstoqueProdutosProductIdRoute
  '/api/v1/inventory/$': typeof ApiV1InventorySplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/crm': typeof CrmRoute
  '/exames': typeof ExamesRoute
  '/financeiro': typeof FinanceiroRoute
  '/pacientes': typeof PacientesRouteWithChildren
  '/prontuario': typeof ProntuarioRoute
  '/vendas': typeof VendasRoute
  '/api/inventory-session': typeof ApiInventorySessionRoute
  '/aplicacoes/nova': typeof AplicacoesNovaRoute
  '/estoque/acesso': typeof EstoqueAcessoRoute
  '/estoque/movimentacoes': typeof EstoqueMovimentacoesRoute
  '/estoque/recebimento': typeof EstoqueRecebimentoRoute
  '/pacientes/$patientId': typeof PacientesPatientIdRoute
  '/aplicacoes': typeof AplicacoesIndexRoute
  '/estoque': typeof EstoqueIndexRoute
  '/estoque/lotes/$lotId': typeof EstoqueLotesLotIdRoute
  '/estoque/produtos/$productId': typeof EstoqueProdutosProductIdRoute
  '/api/v1/inventory/$': typeof ApiV1InventorySplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/aplicacoes': typeof AplicacoesRouteWithChildren
  '/configuracoes': typeof ConfiguracoesRoute
  '/crm': typeof CrmRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/exames': typeof ExamesRoute
  '/financeiro': typeof FinanceiroRoute
  '/pacientes': typeof PacientesRouteWithChildren
  '/prontuario': typeof ProntuarioRoute
  '/vendas': typeof VendasRoute
  '/api/inventory-session': typeof ApiInventorySessionRoute
  '/aplicacoes/nova': typeof AplicacoesNovaRoute
  '/estoque/acesso': typeof EstoqueAcessoRoute
  '/estoque/movimentacoes': typeof EstoqueMovimentacoesRoute
  '/estoque/recebimento': typeof EstoqueRecebimentoRoute
  '/pacientes/$patientId': typeof PacientesPatientIdRoute
  '/aplicacoes/': typeof AplicacoesIndexRoute
  '/estoque/': typeof EstoqueIndexRoute
  '/estoque/lotes/$lotId': typeof EstoqueLotesLotIdRoute
  '/estoque/produtos/$productId': typeof EstoqueProdutosProductIdRoute
  '/api/v1/inventory/$': typeof ApiV1InventorySplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/aplicacoes'
    | '/configuracoes'
    | '/crm'
    | '/estoque'
    | '/exames'
    | '/financeiro'
    | '/pacientes'
    | '/prontuario'
    | '/vendas'
    | '/api/inventory-session'
    | '/aplicacoes/nova'
    | '/estoque/acesso'
    | '/estoque/movimentacoes'
    | '/estoque/recebimento'
    | '/pacientes/$patientId'
    | '/aplicacoes/'
    | '/estoque/'
    | '/estoque/lotes/$lotId'
    | '/estoque/produtos/$productId'
    | '/api/v1/inventory/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/crm'
    | '/exames'
    | '/financeiro'
    | '/pacientes'
    | '/prontuario'
    | '/vendas'
    | '/api/inventory-session'
    | '/aplicacoes/nova'
    | '/estoque/acesso'
    | '/estoque/movimentacoes'
    | '/estoque/recebimento'
    | '/pacientes/$patientId'
    | '/aplicacoes'
    | '/estoque'
    | '/estoque/lotes/$lotId'
    | '/estoque/produtos/$productId'
    | '/api/v1/inventory/$'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/aplicacoes'
    | '/configuracoes'
    | '/crm'
    | '/estoque'
    | '/exames'
    | '/financeiro'
    | '/pacientes'
    | '/prontuario'
    | '/vendas'
    | '/api/inventory-session'
    | '/aplicacoes/nova'
    | '/estoque/acesso'
    | '/estoque/movimentacoes'
    | '/estoque/recebimento'
    | '/pacientes/$patientId'
    | '/aplicacoes/'
    | '/estoque/'
    | '/estoque/lotes/$lotId'
    | '/estoque/produtos/$productId'
    | '/api/v1/inventory/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AplicacoesRoute: typeof AplicacoesRouteWithChildren
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CrmRoute: typeof CrmRoute
  EstoqueRoute: typeof EstoqueRouteWithChildren
  ExamesRoute: typeof ExamesRoute
  FinanceiroRoute: typeof FinanceiroRoute
  PacientesRoute: typeof PacientesRouteWithChildren
  ProntuarioRoute: typeof ProntuarioRoute
  VendasRoute: typeof VendasRoute
  ApiInventorySessionRoute: typeof ApiInventorySessionRoute
  ApiV1InventorySplatRoute: typeof ApiV1InventorySplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aplicacoes': {
      id: '/aplicacoes'
      path: '/aplicacoes'
      fullPath: '/aplicacoes'
      preLoaderRoute: typeof AplicacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exames': {
      id: '/exames'
      path: '/exames'
      fullPath: '/exames'
      preLoaderRoute: typeof ExamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prontuario': {
      id: '/prontuario'
      path: '/prontuario'
      fullPath: '/prontuario'
      preLoaderRoute: typeof ProntuarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inventory-session': {
      id: '/api/inventory-session'
      path: '/api/inventory-session'
      fullPath: '/api/inventory-session'
      preLoaderRoute: typeof ApiInventorySessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aplicacoes/': {
      id: '/aplicacoes/'
      path: '/'
      fullPath: '/aplicacoes/'
      preLoaderRoute: typeof AplicacoesIndexRouteImport
      parentRoute: typeof AplicacoesRoute
    }
    '/aplicacoes/nova': {
      id: '/aplicacoes/nova'
      path: '/nova'
      fullPath: '/aplicacoes/nova'
      preLoaderRoute: typeof AplicacoesNovaRouteImport
      parentRoute: typeof AplicacoesRoute
    }
    '/estoque/': {
      id: '/estoque/'
      path: '/'
      fullPath: '/estoque/'
      preLoaderRoute: typeof EstoqueIndexRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/estoque/acesso': {
      id: '/estoque/acesso'
      path: '/acesso'
      fullPath: '/estoque/acesso'
      preLoaderRoute: typeof EstoqueAcessoRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/estoque/movimentacoes': {
      id: '/estoque/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/estoque/movimentacoes'
      preLoaderRoute: typeof EstoqueMovimentacoesRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/estoque/recebimento': {
      id: '/estoque/recebimento'
      path: '/recebimento'
      fullPath: '/estoque/recebimento'
      preLoaderRoute: typeof EstoqueRecebimentoRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/pacientes/$patientId': {
      id: '/pacientes/$patientId'
      path: '/$patientId'
      fullPath: '/pacientes/$patientId'
      preLoaderRoute: typeof PacientesPatientIdRouteImport
      parentRoute: typeof PacientesRoute
    }
    '/estoque/lotes/$lotId': {
      id: '/estoque/lotes/$lotId'
      path: '/lotes/$lotId'
      fullPath: '/estoque/lotes/$lotId'
      preLoaderRoute: typeof EstoqueLotesLotIdRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/estoque/produtos/$productId': {
      id: '/estoque/produtos/$productId'
      path: '/produtos/$productId'
      fullPath: '/estoque/produtos/$productId'
      preLoaderRoute: typeof EstoqueProdutosProductIdRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/api/v1/inventory/$': {
      id: '/api/v1/inventory/$'
      path: '/api/v1/inventory/$'
      fullPath: '/api/v1/inventory/$'
      preLoaderRoute: typeof ApiV1InventorySplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AplicacoesRouteChildren {
  AplicacoesNovaRoute: typeof AplicacoesNovaRoute
  AplicacoesIndexRoute: typeof AplicacoesIndexRoute
}

const AplicacoesRouteChildren: AplicacoesRouteChildren = {
  AplicacoesNovaRoute: AplicacoesNovaRoute,
  AplicacoesIndexRoute: AplicacoesIndexRoute,
}

const AplicacoesRouteWithChildren = AplicacoesRoute._addFileChildren(
  AplicacoesRouteChildren,
)

interface EstoqueRouteChildren {
  EstoqueAcessoRoute: typeof EstoqueAcessoRoute
  EstoqueMovimentacoesRoute: typeof EstoqueMovimentacoesRoute
  EstoqueRecebimentoRoute: typeof EstoqueRecebimentoRoute
  EstoqueIndexRoute: typeof EstoqueIndexRoute
  EstoqueLotesLotIdRoute: typeof EstoqueLotesLotIdRoute
  EstoqueProdutosProductIdRoute: typeof EstoqueProdutosProductIdRoute
}

const EstoqueRouteChildren: EstoqueRouteChildren = {
  EstoqueAcessoRoute: EstoqueAcessoRoute,
  EstoqueMovimentacoesRoute: EstoqueMovimentacoesRoute,
  EstoqueRecebimentoRoute: EstoqueRecebimentoRoute,
  EstoqueIndexRoute: EstoqueIndexRoute,
  EstoqueLotesLotIdRoute: EstoqueLotesLotIdRoute,
  EstoqueProdutosProductIdRoute: EstoqueProdutosProductIdRoute,
}

const EstoqueRouteWithChildren =
  EstoqueRoute._addFileChildren(EstoqueRouteChildren)

interface PacientesRouteChildren {
  PacientesPatientIdRoute: typeof PacientesPatientIdRoute
}

const PacientesRouteChildren: PacientesRouteChildren = {
  PacientesPatientIdRoute: PacientesPatientIdRoute,
}

const PacientesRouteWithChildren = PacientesRoute._addFileChildren(
  PacientesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AplicacoesRoute: AplicacoesRouteWithChildren,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CrmRoute: CrmRoute,
  EstoqueRoute: EstoqueRouteWithChildren,
  ExamesRoute: ExamesRoute,
  FinanceiroRoute: FinanceiroRoute,
  PacientesRoute: PacientesRouteWithChildren,
  ProntuarioRoute: ProntuarioRoute,
  VendasRoute: VendasRoute,
  ApiInventorySessionRoute: ApiInventorySessionRoute,
  ApiV1InventorySplatRoute: ApiV1InventorySplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
