/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as ConfiguracoesRouteImport } from './routes/configuracoes'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as ExamesRouteImport } from './routes/exames'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as PacientesRouteImport } from './routes/pacientes'
import { Route as ProntuarioRouteImport } from './routes/prontuario'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as EstoqueProdutosProductIdRouteImport } from './routes/estoque/produtos/$productId'
import { Route as EstoqueRecebimentoRouteImport } from './routes/estoque/recebimento'
import { Route as EstoqueMovimentacoesRouteImport } from './routes/estoque/movimentacoes'
import { Route as AplicacoesRouteImport } from './routes/aplicacoes'
import { Route as AplicacoesNovaRouteImport } from './routes/aplicacoes/nova'
import { Route as PacientesPatientIdRouteImport } from './routes/pacientes.$patientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const ExamesRoute = ExamesRouteImport.update({
  id: '/exames',
  path: '/exames',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const PacientesRoute = PacientesRouteImport.update({
  id: '/pacientes',
  path: '/pacientes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProntuarioRoute = ProntuarioRouteImport.update({
  id: '/prontuario',
  path: '/prontuario',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueProdutosProductIdRoute = EstoqueProdutosProductIdRouteImport.update({
  id: '/produtos/$productId',
  path: '/produtos/$productId',
  getParentRoute: () => EstoqueRoute,
} as any)
const EstoqueRecebimentoRoute = EstoqueRecebimentoRouteImport.update({
  id: '/recebimento',
  path: '/recebimento',
  getParentRoute: () => EstoqueRoute,
} as any)
const EstoqueMovimentacoesRoute = EstoqueMovimentacoesRouteImport.update({
  id: '/movimentacoes',
  path: '/movimentacoes',
  getParentRoute: () => EstoqueRoute,
} as any)
const AplicacoesRoute = AplicacoesRouteImport.update({
  id: '/aplicacoes',
  path: '/aplicacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AplicacoesNovaRoute = AplicacoesNovaRouteImport.update({
  id: '/nova',
  path: '/nova',
  getParentRoute: () => AplicacoesRoute,
} as any)
const EstoqueRouteWithChildren = EstoqueRoute._addFileChildren({
  EstoqueProdutosProductIdRoute,
  EstoqueRecebimentoRoute,
  EstoqueMovimentacoesRoute,
})
const AplicacoesRouteWithChildren = AplicacoesRoute._addFileChildren({
  AplicacoesNovaRoute,
})
const PacientesPatientIdRoute = PacientesPatientIdRouteImport.update({
  id: '/$patientId',
  path: '/$patientId',
  getParentRoute: () => PacientesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/crm': typeof CrmRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/estoque/produtos/$productId': typeof EstoqueProdutosProductIdRoute
  '/estoque/recebimento': typeof EstoqueRecebimentoRoute
  '/estoque/movimentacoes': typeof EstoqueMovimentacoesRoute
  '/aplicacoes': typeof AplicacoesRouteWithChildren
  '/aplicacoes/nova': typeof AplicacoesNovaRoute
  '/exames': typeof ExamesRoute
  '/financeiro': typeof FinanceiroRoute
  '/pacientes': typeof PacientesRouteWithChildren
  '/prontuario': typeof ProntuarioRoute
  '/vendas': typeof VendasRoute
  '/pacientes/$patientId': typeof PacientesPatientIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/crm': typeof CrmRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/estoque/produtos/$productId': typeof EstoqueProdutosProductIdRoute
  '/estoque/recebimento': typeof EstoqueRecebimentoRoute
  '/estoque/movimentacoes': typeof EstoqueMovimentacoesRoute
  '/aplicacoes': typeof AplicacoesRouteWithChildren
  '/aplicacoes/nova': typeof AplicacoesNovaRoute
  '/exames': typeof ExamesRoute
  '/financeiro': typeof FinanceiroRoute
  '/pacientes': typeof PacientesRouteWithChildren
  '/prontuario': typeof ProntuarioRoute
  '/vendas': typeof VendasRoute
  '/pacientes/$patientId': typeof PacientesPatientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/configuracoes': typeof ConfiguracoesRoute
  '/crm': typeof CrmRoute
  '/estoque': typeof EstoqueRouteWithChildren
  '/estoque/produtos/$productId': typeof EstoqueProdutosProductIdRoute
  '/estoque/recebimento': typeof EstoqueRecebimentoRoute
  '/estoque/movimentacoes': typeof EstoqueMovimentacoesRoute
  '/aplicacoes': typeof AplicacoesRouteWithChildren
  '/aplicacoes/nova': typeof AplicacoesNovaRoute
  '/exames': typeof ExamesRoute
  '/financeiro': typeof FinanceiroRoute
  '/pacientes': typeof PacientesRouteWithChildren
  '/prontuario': typeof ProntuarioRoute
  '/vendas': typeof VendasRoute
  '/pacientes/$patientId': typeof PacientesPatientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/crm'
    | '/estoque'
    | '/estoque/produtos/$productId'
    | '/estoque/recebimento'
    | '/estoque/movimentacoes'
    | '/aplicacoes'
    | '/aplicacoes/nova'
    | '/exames'
    | '/financeiro'
    | '/pacientes'
    | '/prontuario'
    | '/vendas'
    | '/pacientes/$patientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/crm'
    | '/estoque'
    | '/exames'
    | '/financeiro'
    | '/pacientes'
    | '/prontuario'
    | '/vendas'
    | '/pacientes/$patientId'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/configuracoes'
    | '/crm'
    | '/estoque'
    | '/exames'
    | '/financeiro'
    | '/pacientes'
    | '/prontuario'
    | '/vendas'
    | '/pacientes/$patientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  ConfiguracoesRoute: typeof ConfiguracoesRoute
  CrmRoute: typeof CrmRoute
  EstoqueRoute: typeof EstoqueRouteWithChildren
  AplicacoesRoute: typeof AplicacoesRouteWithChildren
  ExamesRoute: typeof ExamesRoute
  FinanceiroRoute: typeof FinanceiroRoute
  PacientesRoute: typeof PacientesRouteWithChildren
  ProntuarioRoute: typeof ProntuarioRoute
  VendasRoute: typeof VendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracoes': {
      id: '/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof ConfiguracoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque/produtos/$productId': {
      id: '/estoque/produtos/$productId'
      path: '/produtos/$productId'
      fullPath: '/estoque/produtos/$productId'
      preLoaderRoute: typeof EstoqueProdutosProductIdRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/estoque/recebimento': {
      id: '/estoque/recebimento'
      path: '/recebimento'
      fullPath: '/estoque/recebimento'
      preLoaderRoute: typeof EstoqueRecebimentoRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/estoque/movimentacoes': {
      id: '/estoque/movimentacoes'
      path: '/movimentacoes'
      fullPath: '/estoque/movimentacoes'
      preLoaderRoute: typeof EstoqueMovimentacoesRouteImport
      parentRoute: typeof EstoqueRoute
    }
    '/aplicacoes': {
      id: '/aplicacoes'
      path: '/aplicacoes'
      fullPath: '/aplicacoes'
      preLoaderRoute: typeof AplicacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aplicacoes/nova': {
      id: '/aplicacoes/nova'
      path: '/nova'
      fullPath: '/aplicacoes/nova'
      preLoaderRoute: typeof AplicacoesNovaRouteImport
      parentRoute: typeof AplicacoesRoute
    }
    '/exames': {
      id: '/exames'
      path: '/exames'
      fullPath: '/exames'
      preLoaderRoute: typeof ExamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes': {
      id: '/pacientes'
      path: '/pacientes'
      fullPath: '/pacientes'
      preLoaderRoute: typeof PacientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prontuario': {
      id: '/prontuario'
      path: '/prontuario'
      fullPath: '/prontuario'
      preLoaderRoute: typeof ProntuarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pacientes/$patientId': {
      id: '/pacientes/$patientId'
      path: '/$patientId'
      fullPath: '/pacientes/$patientId'
      preLoaderRoute: typeof PacientesPatientIdRouteImport
      parentRoute: typeof PacientesRoute
    }
  }
}

interface PacientesRouteChildren {
  PacientesPatientIdRoute: typeof PacientesPatientIdRoute
}

const PacientesRouteChildren: PacientesRouteChildren = {
  PacientesPatientIdRoute: PacientesPatientIdRoute,
}

const PacientesRouteWithChildren = PacientesRoute._addFileChildren(
  PacientesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  CrmRoute: CrmRoute,
  EstoqueRoute: EstoqueRouteWithChildren,
  AplicacoesRoute: AplicacoesRouteWithChildren,
  ExamesRoute: ExamesRoute,
  FinanceiroRoute: FinanceiroRoute,
  PacientesRoute: PacientesRouteWithChildren,
  ProntuarioRoute: ProntuarioRoute,
  VendasRoute: VendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
